var mongoose = require('mongoose');
const shortid = require('shortid');
var path = require('path');
var venuesSchema = require(path.join(__dirname, 'venues'));
var categoryTypeSchema = mongoose.Schema({
  article_page: {type:String},
  category_type_article:{type:String},
  'Visual_arts': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      category_type_article: {type:String},
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Fairs: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Auctions: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      category_type_article: {type:String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Galleries: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Museums: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      category_type_article: {type:String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Columnist: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Features: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      field_entity_profile_location: venuesSchema,
      field_event_date: {type:Date,default: Date.now},
      category_type_article: {type:String},
      field_event_date_to: {type:Date,default: Date.now},
      files:[],
      sub_cat_label:[]
    }]
  },
  "Architecture_design": {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Architecture: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Design: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'Home_Interiors': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      field_entity_profile_location: venuesSchema,
      field_event_date: {type:Date,default: Date.now},
      category_type_article: {type:String},
      field_event_date_to: {type:Date,default: Date.now},
      files:[],
      sub_cat_label:[]
    }]
  },
  "Performance_arts": {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      category_type_article: {type:String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Film: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Music: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Television: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'Theatre_Dance': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      category_type_article: {type:String},
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      field_entity_profile_location: venuesSchema,
      field_event_date: {type:Date,default: Date.now},
      field_event_date_to: {type:Date,default: Date.now},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  'Lifestyle': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      category_type_article: {type:String},
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'Food_Wine': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'Jewelry_Watches': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'Autos_Boats': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Auctions:[{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      category_type_article: {type:String},
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      field_entity_profile_location: venuesSchema,
      field_event_date: {type:Date,default: Date.now},
      field_event_date_to: {type:Date,default: Date.now},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  'Fashion': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      category_type_article: {type:String},
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Designer_Spotlight: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Runway: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      category_type_article: {type:String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Style_Guide: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Accessories: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      category_type_article: {type:String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    Exhibitions:[{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]

    }],
    'Event':[{
      title:{type:String},
      field_entity_profile_location: venuesSchema,
      field_event_date: {type:Date,default: Date.now},
      category_type_article: {type:String},
      field_event_date_to: {type:Date,default: Date.now},
      files:[],
      sub_cat_label:[]
    }]
  },
  "Travel": {
    latestArticle: [{
      sub_cat_label: {type: String},
      category_type_article: {type:String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
   _id:false  }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      category_type_article: {type:String},
      files:[],
      sub_cat_label:[]
    }],
    People: [{
       sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      category_type_article: {type:String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }],
    Destinations: [{
       sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }],
    Inspiration: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      category_type_article: {type:String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: Date,default: Date.now},
    }]
  },

})


var categoryTypeSchemaModel = mongoose.model('categoryTypeModel', categoryTypeSchema);
