var mongoose = require('mongoose');
const shortid = require('shortid');

var categoryTypeSchema = mongoose.Schema({
  'Visual_arts': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Fairs: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Auctions: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Galleries: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Museums: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Columnist: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Features: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  "Architecture_design": {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Architecture: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Design: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'Home_Interiors': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  "Performance_arts": {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Film: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Music: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Television: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'Theatre_Dance': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
    }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  'Lifestyle': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'Food_Wine': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'Jewelry_Watches': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'Autos_Boats': [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Auctions:[{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      files:[],
      sub_cat_label:[]
    }]
  },
  'Fashion': {
    latestArticle: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Designer_Spotlight: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Runway: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Style_Guide: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Accessories: [{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    Exhibitions:[{
      sub_cat_label: {type: String},
      ArticleId: {type: String},
      title: {type: String},
      short_title: {type: String},
      summary: {type: String},
      files: [],
      author_article: [],
      added_date: {type: String},
   _id:false  }],
    'SlideShow':[{
      title:{type:String},
      shortTitle:{type:String},
      files:[],
      sub_cat_label:[]
    }],
    'Event':[{
      title:{type:String},
      files:[],
      sub_cat_label:[]
    }]
  },

})


var categoryTypeSchemaModel = mongoose.model('categoryTypeModel', categoryTypeSchema);
