module.exports = [{
	  entityType: {type: String,required:true},
     language:{type:String},
     enitity_array_location:[{
          locationName:{type:String,required:true},
          street:{type:String,required:true},
          additional:{type:String},
          country:{type:String,required:true},
          stateProvince:{type:String},
          city:{type:String},
          postalCode:{type:String},
          latitude:{type:String},
          longitude:{type:String},
          neighborhood:{type:String},
          locationPhone:{type:String},
          locationFax: {type:String},
          locationEmail: {type:String},
          openingHoursAlternative:{type:String},
          region:{type:String},
     }],
     entityName: {type:String,required:true},
     websiteTitle:{type:String},
     added_date:{type: Date,default: Date.now},
     file:[],
 }];
