var mongoose = require('mongoose');
var ObjectId = require('mongoose').Schema.Types.ObjectId;
var path = require('path');

var ArtworkSchema = mongoose.Schema({
     entityLocation: [],
     title:{type:String},
     artworkType: {type:String},
    field_artists: [{
          artistName: {type: String},
     language:{type:String},
     articleDescription: {type:String},
     fname:{type:String},
     added_date:{type: Date,default: Date.now},
     lname:{type:String},
     show_date:{type:String},
     knownas:{type:String},
     files:[],
     nationality:{type:String},
     photo_credit:{type:String},
     artist_statement:{type:String},
     field_country:{type:String},
     field_specialties:[{type:String}],
     fomat_date:{type:String},
     tofomat_date:{type:String},
     field_birth_year_qualifier:{type:String},
     field_death_year_quallifier:{type:String},
     place_of_birth:{type:String},
     place_of_death:{type:String},
     date_description:{type:String},
     articleDescription: {type:String},
     seo_keywords: {type:String},
     authored_by:{type:String},
     authored_on:{type:String},
     published:{type:String},
     seo_description:{type:String},
     seo_title:{type:String},
    }],
     language:{type:String},
     img_height:{type: String},
     img_width:{type:String},
     files:[],
     img_depth:{type:String},
     img_units:{type:String},
     img_measurmentDescription:{type:String},
     img_mediumCategory:{type:String},
     material:{type:String},
     edition:{type:String},
     circa:{type:String},
     start_date:{type:String},
     date_dateQualifier:{type:String},
     artWorkSpecialties:[{type:String}],
     date_subject:{type:String},
     date_status:{type:String},
     date_priceFrom:{type:String},
     date_priceTo:{type:String},
     currency:{type:String},
     extraDescription:{type:String},
     seo_keywords: {type:String},
     authored_by:{type:String},
     authored_on:{type:String},
     published:{type:Boolean},
     seo_description:{type:String},
     artwork_order:{type:String},
     createdBy:{type:String}
     
    });

var artworkModel = mongoose.model('artworkModel', ArtworkSchema);
