module.exports = [{
     entityLocation: {type: String},
     title:{type:String},
     artworkType: {type:String},
     language:{type:String},
     img_height:{type: String},
     img_width:{type:String},
     img_depth:{type:String},
     img_units:{type:String},
     img_measurmentDescription:{type:String},
     img_mediumCategory:{type:String},
     material:{type:String},
     edition:{type:String},
     date_dateQualifier:{type:String},
     artWorkSpecialties:[{type:String}],
     date_subject:{type:String},
     date_status:{type:String},
     date_priceFrom:{type:String},
     date_priceTo:{type:String},
     currency:{type:String},
     extraDescription:{type:String},
     seo_keywords: {type:String},
     authored_by:{type:String},
     authored_on:{type:String},
     published:{type:String},
     seo_description:{type:String},
     artwork_order:{type:String},
}];